/*!
 * Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import * as vscode from 'vscode'

/* eslint-disable @typescript-eslint/naming-convention */

const coefficients: Record<string, number> = {
    '¸': 1.8196,
    8: -1.7709,
    '\\': -1.3587,
    '#': -1.2401,
    '/': -1.2015,
    extends: 1.1802,
    7: -1.1705,
    except: 1.0983,
    5: -1.027,
    0: -0.9815,
    6: -0.9683,
    new: -0.9565,
    case: 0.9511,
    int: -0.9447,
    '\n': 0.9139,
    9: -0.9003,
    '*': -0.889,
    ':': 0.837,
    '~': -0.8122,
    '{': 0.793,
    interface: 0.7503,
    x: 0.718,
    B: 0.7094,
    '`': -0.6876,
    ' ': 0.6736,
    static: -0.6634,
    2: -0.6616,
    K: -0.6566,
    default: 0.6566,
    ',': 0.6513,
    z: 0.6277,
    $: -0.6183,
    X: 0.6129,
    this: 0.6107,
    elif: 0.6092,
    W: -0.6082,
    do: -0.5891,
    1: -0.5834,
    D: -0.5661,
    '£': -0.5417,
    ';': 0.5192,
    v: 0.4972,
    del: 0.4915,
    float: 0.4867,
    H: 0.4544,
    try: -0.4512,
    final: -0.4463,
    U0001faa8: -0.4427,
    4: -0.4412,
    '|': 0.4398,
    '-': -0.4344,
    raise: 0.434,
    é: 0.4336,
    d: 0.4333,
    Z: -0.4326,
    u: 0.4253,
    f: 0.424,
    yield: 0.4226,
    o: 0.4174,
    continue: -0.4084,
    '<': 0.4049,
    catch: -0.3979,
    '(': 0.3959,
    m: 0.3851,
    '√': 0.3829,
    Y: 0.3823,
    '!': -0.3812,
    'Ⓡ': 0.3783,
    ｎ: 0.3707,
    '。': -0.3686,
    ą: 0.366,
    i: 0.3521,
    G: 0.3516,
    from: -0.3494,
    '%': -0.3472,
    b: 0.3469,
    い: -0.3459,
    ö: 0.3451,
    '≈': -0.344,
    '@': -0.3406,
    short: -0.3385,
    U: 0.338,
    e: 0.33,
    k: 0.3197,
    n: 0.3158,
    Q: -0.3123,
    ß: -0.3119,
    ㅊ: -0.3117,
    else: -0.2959,
    a: 0.2954,
    c: 0.2953,
    void: -0.2878,
    '.': -0.2844,
    None: 0.2808,
    r: 0.2761,
    '\xa0': 0.2753,
    global: 0.274,
    long: 0.2636,
    '￥': -0.2584,
    ']': -0.2579,
    private: -0.2551,
    y: 0.2544,
    w: 0.2531,
    l: 0.253,
    True: 0.2528,
    def: 0.2461,
    '"': 0.245,
    N: -0.2361,
    O: 0.2335,
    t: 0.2313,
    or: 0.2288,
    g: 0.225,
    abstract: -0.2236,
    _: 0.2227,
    break: -0.2184,
    数: 0.2128,
    enum: 0.2076,
    置: -0.2061,
    lambda: 0.2054,
    '?': 0.2052,
    char: -0.2036,
    M: 0.1982,
    줄: -0.1973,
    ト: -0.1947,
    을: -0.1943,
    ㅕ: -0.1938,
    ')': -0.1928,
    import: -0.1918,
    삿: -0.1915,
    ㄱ: -0.1911,
    instanceof: -0.1873,
    '¿': -0.1871,
    배: -0.1869,
    '¥': -0.1868,
    す: -0.1867,
    package: 0.1866,
    I: 0.1819,
    ん: -0.1803,
    not: 0.1802,
    で: -0.1795,
    '🗿': -0.179,
    '+': -0.1785,
    ス: -0.1783,
    되: -0.1756,
    凶: -0.1753,
    ｋ: -0.1748,
    ã: -0.1722,
    く: -0.1717,
    خ: -0.1715,
    Ð: -0.1713,
    '^': -0.1679,
    를: -0.1677,
    算: -0.1642,
    in: -0.164,
    값: -0.1635,
    も: -0.1609,
    E: -0.1593,
    with: 0.1546,
    の: -0.1544,
    함: -0.1543,
    throws: 0.1524,
    P: -0.1502,
    J: 0.1493,
    j: 0.1491,
    p: 0.1479,
    s: 0.1387,
    竹: -0.1351,
    '💻': -0.1315,
    V: -0.129,
    R: -0.1266,
    return: 0.1215,
    await: -0.1187,
    밸: -0.1154,
    '}': 0.115,
    F: -0.1139,
    Д: -0.1132,
    assert: 0.106,
    q: 0.1043,
    for: 0.1014,
    public: -0.0998,
    if: 0.0944,
    A: 0.0917,
    pass: -0.0785,
    '[': -0.0757,
    class: -0.0744,
    '>': -0.0741,
    L: 0.0705,
    '=': -0.0604,
    "'": 0.0489,
    3: -0.0486,
    h: 0.0407,
    while: 0.0328,
    throw: -0.0314,
    is: 0.0301,
    C: 0.0288,
    and: 0.027,
    を: -0.0229,
    as: 0.0207,
}

// os coefficient
const osMap: Record<string, number> = {
    'Mac OS X': 0.2764,
    win32: 0.1828,
}

// trigger type coefficient
const triggerTypeCoefficientMap: Record<string, number> = {
    IntelliSenseAcceptance: 0.1503,
    SpecialCharacters: 0.4069,
    Enter: 0.7666,
}

// other metadata coefficient
const lineNumCoefficient = 1.4767

const cursorOffsetCoefficient = -1.2952

// length of the current line of left_context
const lengthOfLeftCurrentCoefficient = -1.647

// length of the previous line of left context
const lengthOfLeftPrevCoefficient = 0.4337

// lenght of right_context
const lengthofRightCoefficient = -0.6964

// intercept of logistic regression classifier
const intercept = -0.77428556

// maxx[0]
const maxCursorOffset = 94228

// maxx[1]
const maxLineNum = 2250

// maxx[2]
const maxLengthOfLeftCurrent = 177

// maxx[3]
const maxLengthOfLeftPrev = 152

// maxx[4]
const maxLengthofRight = 10239

export const getShouldTrigger = (
    leftContext: string,
    rightContext: string,
    os: string,
    triggerType: string | undefined,
    char: string,
    lineNum: number,
    cursorOffset: number,
    triggerThreshold: number
) => {
    const threshold =
        100 - (vscode.workspace.getConfiguration('aws.codewhisperer').get('classifierInvocationProbability') as number)
    const myRandom = randomIntegerBetween(0, 101)
    if (myRandom < threshold) {
        return
    }

    const leftContextLines = leftContext.split(/\r?\n/)
    const leftContextAtCurrentLine = leftContextLines[leftContextLines.length - 1]
    const tokens = leftContextAtCurrentLine.trim().split(' ')
    const keyword = tokens[tokens.length - 1]
    const lengthOfLeftCurrent = leftContextLines[leftContextLines.length - 1].length
    const lengthOfLeftPrev = leftContextLines[leftContextLines.length - 2]?.length ?? 0
    const lengthofRight = rightContext.trim().length
    const triggerTypeCoefficient = triggerTypeCoefficientMap[triggerType || ''] ?? 0
    const osCoefficient = osMap[os] ?? 0
    const charCoefficient = coefficients[char] ?? 0
    const keyWordCoefficient = coefficients[keyword] ?? 0
    const result =
        lengthofRight * (lengthofRightCoefficient / maxLengthofRight) +
        lengthOfLeftCurrent * (lengthOfLeftCurrentCoefficient / maxLengthOfLeftCurrent) +
        lengthOfLeftPrev * (lengthOfLeftPrevCoefficient / maxLengthOfLeftPrev) +
        lineNumCoefficient * (lineNum / maxLineNum) +
        cursorOffsetCoefficient * (cursorOffset / maxCursorOffset) +
        osCoefficient +
        triggerTypeCoefficient +
        charCoefficient +
        keyWordCoefficient +
        intercept

    const shouldTrigger = sigmoid(result) > triggerThreshold
    return shouldTrigger
}

const sigmoid = (x: number) => {
    return 1 / (1 + Math.exp(-x))
}

// min(inclusive); max(exclusive)
function randomIntegerBetween(min: number, max: number) {
    return Math.floor(Math.random() * (max - min) + min)
}

const keyWords: Record<string, string[]> = {
    python_keywords: [
        'False',
        'await',
        'else',
        'import',
        'pass',
        'None',
        'break',
        'except',
        'in',
        'raise',
        'True',
        'class',
        'finally',
        'is',
        'return',
        'and',
        'continue',
        'for',
        'lambda',
        'try',
        'as',
        'def',
        'from',
        'nonlocal',
        'while',
        'assert',
        'del',
        'global',
        'not',
        'with',
        'async',
        'elif',
        'if',
        'or',
        'yield',
    ],
    java_keywords: [
        'abstract',
        'assert',
        'boolean',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'class',
        'const',
        'continue',
        'default',
        'do',
        'double',
        'else',
        'enum',
        'extends',
        'final',
        'finally',
        'float',
        'for',
        'goto',
        'if',
        'implements',
        'import',
        'instanceof',
        'int',
        'interface',
        'long',
        'native',
        'new',
        'package',
        'private',
        'protected',
        'public',
        'return',
        'short',
        'static',
        'strictfp',
        'super',
        'switch',
        'synchronized',
        'this',
        'throw',
        'throws',
        'transient',
        'try',
        'void',
        'volatile',
        'while',
    ],
    javascript_keywords: [
        'abstract',
        'arguments',
        'await',
        'boolean',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'class',
        'const',
        'continue',
        'debugger',
        'default',
        'delete',
        'do',
        'double',
        'else',
        'enum',
        'eval',
        'export',
        'extends',
        'false',
        'final',
        'finally',
        'float',
        'for',
        'function',
        'goto',
        'if',
        'implements',
        'import',
        'in',
        'instanceof',
        'int',
        'interface',
        'interface',
        'let',
        'long',
        'native',
        'new',
        'null',
        'package',
        'private',
        'protected',
        'public',
        'return',
        'short',
        'static',
        'super',
        'switch',
        'synchronized',
        'this',
        'throw',
        'throws',
        'transient',
        'true',
        'try',
        'typeof',
        'var',
        'void',
        'volatile',
        'while',
        'with',
        'yield',
    ],
    typescript_keywords: [
        'break',
        'as',
        'any',
        'switch',
        'case',
        'if',
        'throw',
        'else',
        'var',
        'number',
        'string',
        'get',
        'module',
        'type',
        'instanceof',
        'typeof',
        'public',
        'private',
        'enum',
        'export',
        'finally',
        'for',
        'while',
        'void',
        'null',
        'super',
        'this',
        'new',
        'in',
        'return',
        'true',
        'false',
        'any',
        'extends',
        'static',
        'let',
        'package',
        'implements',
        'interface',
        'function',
        'new',
        'try',
        'yield',
        'const',
        'continue',
        'do',
        'catch',
    ],
    csharp_keywords: [
        'abstract',
        'as',
        'base',
        'bool',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'checked',
        'class',
        'const',
        'continue',
        'decimal',
        'default',
        'delegate',
        'do',
        'double',
        'else',
        'enum',
        'event',
        'explicit',
        'extern',
        'false',
        'finally',
        'fixed',
        'float',
        'for',
        'foreach',
        'goto',
        'if',
        'implicit',
        'in',
        'int',
        'interface',
        'internal',
        'is',
        'lock',
        'long',
        'namespace',
        'new',
        'null',
        'object',
        'operator',
        'out',
        'override',
        'params',
        'private',
        'protected',
        'public',
        'readonly',
        'ref',
        'return',
        'sbyte',
        'sealed',
        'short',
        'sizeof',
        'stackalloc',
        'static',
        'string',
        'struct',
        'switch',
        'this',
        'throw',
        'true',
        'try',
        'typeof',
        'uint',
        'ulong',
        'unchecked',
        'unsafe',
        'ushort',
        'using',
        'virtual',
        'void',
        'volatile',
        'while',
    ],
}
